// ============================================================================
// PeptideRx — Peptide Library & Default Protocol Data
// ============================================================================

window.PEPTIDE_CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'fat_loss', label: 'Fat Loss' },
  { id: 'muscle', label: 'Muscle Building' },
  { id: 'recovery', label: 'Recovery' },
  { id: 'anti_aging', label: 'Anti-Aging' },
  { id: 'sexual_health', label: 'Sexual Health' },
  { id: 'hormone', label: 'Hormone Support' },
];

window.CATEGORY_COLORS = {
  fat_loss: '#ef4444',
  muscle: '#3b82f6',
  recovery: '#22c55e',
  anti_aging: '#a855f7',
  sexual_health: '#ec4899',
  hormone: '#f59e0b',
};

window.INJECTION_SITES = [
  { id: 'abdomen_left', label: 'Abdomen (Left)', region: 'abdomen' },
  { id: 'abdomen_right', label: 'Abdomen (Right)', region: 'abdomen' },
  { id: 'thigh_left', label: 'Thigh (Left)', region: 'thigh' },
  { id: 'thigh_right', label: 'Thigh (Right)', region: 'thigh' },
  { id: 'deltoid_left', label: 'Deltoid (Left)', region: 'arm' },
  { id: 'deltoid_right', label: 'Deltoid (Right)', region: 'arm' },
  { id: 'glute_left', label: 'Glute (Left)', region: 'glute' },
  { id: 'glute_right', label: 'Glute (Right)', region: 'glute' },
];

window.PEPTIDE_LIBRARY = [
  {
    id: 'retatrutide',
    name: 'Retatrutide',
    fullName: 'Retatrutide (LY3437943)',
    aliases: ['Reta', 'LY3437943', 'Triple G'],
    category: 'fat_loss',
    fdaApproved: false,
    safetyRating: 3,
    mechanism: 'Triple agonist targeting GIP, GLP-1, and glucagon receptors. Reduces appetite, increases energy expenditure, and promotes fat oxidation through three complementary metabolic pathways.',
    benefits: ['Significant weight loss (up to 24% in trials)', 'Appetite suppression', 'Improved glycemic control', 'Enhanced fat oxidation', 'Potential cardiovascular benefits'],
    sideEffects: ['Nausea (dose-dependent)', 'Diarrhea', 'Vomiting', 'Decreased appetite', 'Injection site reactions', 'Constipation'],
    typicalDose: { min: 1, max: 12, unit: 'mg', startingDose: '1mg, titrate up' },
    frequency: 'Weekly',
    cycleLength: '24-48 weeks',
    halfLife: '~6 days',
    injectionType: 'Subcutaneous',
    timing: 'Any time of day, same day each week',
    reconstitution: { powderMg: 8, waterMl: 2, concentrationPerMl: '4mg/mL' },
    storage: { refrigerated: true, shelfLife: '28 days reconstituted', freezer: 'Up to 6 months lyophilized' },
    stacksWith: ['tesamorelin', 'bpc-157'],
    contraindications: ['Personal/family history of medullary thyroid carcinoma', 'MEN 2 syndrome', 'Pregnancy'],
  },
  {
    id: 'tesamorelin',
    name: 'Tesamorelin',
    fullName: 'Tesamorelin Acetate (Egrifta)',
    aliases: ['Tesa', 'Egrifta', 'TH9507'],
    category: 'fat_loss',
    fdaApproved: true,
    safetyRating: 4,
    mechanism: 'Growth hormone-releasing hormone (GHRH) analog that stimulates pituitary gland to produce and release natural growth hormone, specifically targeting visceral adipose tissue reduction.',
    benefits: ['Reduces visceral fat', 'Increases IGF-1 levels', 'Improves body composition', 'May improve cognitive function', 'FDA-approved safety profile'],
    sideEffects: ['Injection site reactions', 'Joint pain', 'Peripheral edema', 'Hyperglycemia', 'Carpal tunnel symptoms'],
    typicalDose: { min: 1, max: 2, unit: 'mg', startingDose: '2mg daily' },
    frequency: 'Daily',
    cycleLength: '12-26 weeks, can cycle',
    halfLife: '26 minutes (but GH pulse lasts hours)',
    injectionType: 'Subcutaneous',
    timing: 'Before bed on empty stomach (2+ hours fasted)',
    reconstitution: { powderMg: 2, waterMl: 2, concentrationPerMl: '1mg/mL' },
    storage: { refrigerated: true, shelfLife: '14 days reconstituted', freezer: 'Until expiry lyophilized' },
    stacksWith: ['ipamorelin', 'bpc-157', 'ghk-cu'],
    contraindications: ['Active malignancy', 'Hypersensitivity to GHRH', 'Pregnancy', 'Pituitary surgery/disease'],
  },
  {
    id: 'ipamorelin',
    name: 'Ipamorelin',
    fullName: 'Ipamorelin Acetate',
    aliases: ['Ipa', 'IPA'],
    category: 'muscle',
    fdaApproved: false,
    safetyRating: 4,
    mechanism: 'Selective growth hormone secretagogue that mimics ghrelin and binds to GHSR receptors in the pituitary, triggering natural GH pulses without significantly affecting cortisol or prolactin.',
    benefits: ['Increases growth hormone release', 'Supports muscle growth', 'Improves recovery', 'Enhances sleep quality', 'Gentle side effect profile'],
    sideEffects: ['Headache', 'Water retention (mild)', 'Tingling/numbness', 'Increased hunger (mild)', 'Lightheadedness'],
    typicalDose: { min: 100, max: 300, unit: 'mcg', startingDose: '200mcg' },
    frequency: 'Daily (1-3x)',
    cycleLength: '8-12 weeks on, 4 weeks off',
    halfLife: '~2 hours',
    injectionType: 'Subcutaneous',
    timing: 'Before bed on empty stomach, or post-workout',
    reconstitution: { powderMg: 5, waterMl: 2.5, concentrationPerMl: '2mg/mL' },
    storage: { refrigerated: true, shelfLife: '21 days reconstituted', freezer: 'Up to 12 months lyophilized' },
    stacksWith: ['cjc-1295', 'tesamorelin', 'bpc-157'],
    contraindications: ['Active cancer', 'Pregnancy', 'Pituitary disorders'],
  },
  {
    id: 'cjc-1295',
    name: 'CJC-1295',
    fullName: 'CJC-1295 (with or without DAC)',
    aliases: ['CJC', 'Modified GRF 1-29', 'Mod GRF'],
    category: 'muscle',
    fdaApproved: false,
    safetyRating: 4,
    mechanism: 'Synthetic GHRH analog that stimulates sustained growth hormone release from the pituitary. The DAC (Drug Affinity Complex) version extends half-life significantly for less frequent dosing.',
    benefits: ['Sustained GH elevation', 'Increased muscle mass', 'Improved fat metabolism', 'Enhanced recovery', 'Better sleep quality'],
    sideEffects: ['Flushing', 'Headache', 'Water retention', 'Drowsiness', 'Tingling extremities'],
    typicalDose: { min: 100, max: 300, unit: 'mcg', startingDose: '100mcg (no DAC) or 2mg (with DAC)' },
    frequency: 'Daily (no DAC) or 2x/week (with DAC)',
    cycleLength: '12 weeks on, 4 weeks off',
    halfLife: '30 min (no DAC) / 8 days (with DAC)',
    injectionType: 'Subcutaneous',
    timing: 'Before bed on empty stomach',
    reconstitution: { powderMg: 5, waterMl: 2.5, concentrationPerMl: '2mg/mL' },
    storage: { refrigerated: true, shelfLife: '21 days reconstituted', freezer: 'Up to 12 months lyophilized' },
    stacksWith: ['ipamorelin', 'tesamorelin'],
    contraindications: ['Active cancer', 'Pregnancy', 'Pituitary tumors'],
  },
  {
    id: 'bpc-157',
    name: 'BPC-157',
    fullName: 'Body Protection Compound-157',
    aliases: ['BPC', 'Bepecin', 'PL 14736'],
    category: 'recovery',
    fdaApproved: false,
    safetyRating: 4,
    mechanism: 'Pentadecapeptide derived from human gastric juice. Promotes angiogenesis, accelerates wound healing, and modulates the nitric oxide system. Protects and heals GI tract lining and promotes tendon/ligament repair.',
    benefits: ['Accelerates injury healing', 'Reduces inflammation', 'Gut healing and protection', 'Tendon and ligament repair', 'Neuroprotective properties'],
    sideEffects: ['Nausea (rare)', 'Dizziness (rare)', 'Headache (rare)', 'Generally very well tolerated'],
    typicalDose: { min: 250, max: 500, unit: 'mcg', startingDose: '250mcg 2x/day' },
    frequency: 'Daily (1-2x)',
    cycleLength: '4-12 weeks',
    halfLife: '~4 hours',
    injectionType: 'Subcutaneous (near injury site preferred)',
    timing: 'Any time, can split AM/PM dose',
    reconstitution: { powderMg: 5, waterMl: 2, concentrationPerMl: '2.5mg/mL' },
    storage: { refrigerated: true, shelfLife: '30 days reconstituted', freezer: 'Up to 12 months lyophilized' },
    stacksWith: ['tb-500', 'ghk-cu'],
    contraindications: ['Active cancer (theoretical)', 'Pregnancy'],
  },
  {
    id: 'tb-500',
    name: 'TB-500',
    fullName: 'Thymosin Beta-4 Fragment',
    aliases: ['TB4', 'Thymosin Beta 4', 'TB500'],
    category: 'recovery',
    fdaApproved: false,
    safetyRating: 4,
    mechanism: 'Synthetic peptide of the naturally occurring thymosin beta-4. Promotes cell migration, blood vessel formation, and tissue repair through upregulation of actin and stem cell activation.',
    benefits: ['Accelerates wound healing', 'Reduces inflammation', 'Promotes flexibility', 'Supports cardiac repair', 'Hair regrowth potential'],
    sideEffects: ['Headache', 'Lethargy (temporary)', 'Head rush', 'Generally well tolerated'],
    typicalDose: { min: 2, max: 5, unit: 'mg', startingDose: '2.5mg 2x/week' },
    frequency: '2-3x per week (loading), then 2x/week',
    cycleLength: '4-8 weeks loading, then maintenance',
    halfLife: '~2 hours',
    injectionType: 'Subcutaneous',
    timing: 'Any time of day',
    reconstitution: { powderMg: 5, waterMl: 2, concentrationPerMl: '2.5mg/mL' },
    storage: { refrigerated: true, shelfLife: '21 days reconstituted', freezer: 'Up to 12 months lyophilized' },
    stacksWith: ['bpc-157', 'ghk-cu'],
    contraindications: ['Active cancer', 'Pregnancy'],
  },
  {
    id: 'ghk-cu',
    name: 'GHK-Cu',
    fullName: 'Copper Peptide GHK-Cu',
    aliases: ['Copper Peptide', 'GHK Copper'],
    category: 'anti_aging',
    fdaApproved: false,
    safetyRating: 4,
    mechanism: 'Naturally occurring copper-binding tripeptide that activates tissue remodeling genes, promotes collagen synthesis, and functions as a potent antioxidant and anti-inflammatory agent.',
    benefits: ['Promotes collagen synthesis', 'Skin rejuvenation', 'Hair growth stimulation', 'Wound healing', 'Antioxidant protection', 'Anti-inflammatory'],
    sideEffects: ['Injection site redness', 'Mild skin irritation (topical)', 'Generally very well tolerated'],
    typicalDose: { min: 1, max: 3, unit: 'mg', startingDose: '1-2mg daily' },
    frequency: 'Daily',
    cycleLength: '8-12 weeks, cycle off 4 weeks',
    halfLife: '~1 hour',
    injectionType: 'Subcutaneous',
    timing: 'Any time of day',
    reconstitution: { powderMg: 50, waterMl: 5, concentrationPerMl: '10mg/mL' },
    storage: { refrigerated: true, shelfLife: '30 days reconstituted', freezer: 'Up to 24 months lyophilized' },
    stacksWith: ['bpc-157', 'tb-500'],
    contraindications: ['Copper sensitivity', 'Wilsons disease', 'Pregnancy'],
  },
  {
    id: 'pt-141',
    name: 'PT-141',
    fullName: 'Bremelanotide (Vyleesi)',
    aliases: ['Bremelanotide', 'Vyleesi', 'PT141'],
    category: 'sexual_health',
    fdaApproved: true,
    safetyRating: 3,
    mechanism: 'Melanocortin receptor agonist (MC3R and MC4R) that works through the central nervous system to increase sexual desire. Unlike PDE5 inhibitors, it acts on the brain rather than vascular system.',
    benefits: ['Increases sexual desire', 'Treats hypoactive sexual desire disorder', 'Works for both men and women', 'Central nervous system mechanism'],
    sideEffects: ['Nausea (common)', 'Flushing', 'Headache', 'Injection site reactions', 'Temporary skin darkening', 'Blood pressure changes'],
    typicalDose: { min: 0.5, max: 2, unit: 'mg', startingDose: '1.75mg as needed' },
    frequency: 'As needed (max 1x per 24 hours)',
    cycleLength: 'As needed, no cycling required',
    halfLife: '~2.7 hours',
    injectionType: 'Subcutaneous',
    timing: '45 minutes before activity',
    reconstitution: { powderMg: 10, waterMl: 2, concentrationPerMl: '5mg/mL' },
    storage: { refrigerated: true, shelfLife: '30 days reconstituted', freezer: 'Until expiry lyophilized' },
    stacksWith: [],
    contraindications: ['Uncontrolled hypertension', 'Cardiovascular disease', 'Pregnancy'],
  },
  {
    id: 'mk-677',
    name: 'MK-677',
    fullName: 'Ibutamoren Mesylate',
    aliases: ['Ibutamoren', 'Nutrobal', 'MK677'],
    category: 'muscle',
    fdaApproved: false,
    safetyRating: 3,
    mechanism: 'Non-peptide ghrelin receptor agonist that stimulates growth hormone secretion. Taken orally, it provides sustained GH and IGF-1 elevation without suppressing natural production.',
    benefits: ['Increases GH and IGF-1', 'Improves sleep quality', 'Increases appetite', 'Supports muscle growth', 'Improves bone density', 'Oral dosing (not injection)'],
    sideEffects: ['Increased appetite', 'Water retention', 'Lethargy', 'Numbness in hands', 'Blood sugar elevation', 'Joint pain'],
    typicalDose: { min: 10, max: 25, unit: 'mg', startingDose: '10mg oral daily' },
    frequency: 'Daily (oral)',
    cycleLength: '8-16 weeks, or ongoing at low dose',
    halfLife: '~24 hours',
    injectionType: 'Oral',
    timing: 'Before bed (reduces daytime lethargy)',
    reconstitution: null,
    storage: { refrigerated: false, shelfLife: 'Per bottle expiry', freezer: 'Not required' },
    stacksWith: ['ipamorelin', 'cjc-1295'],
    contraindications: ['Diabetes (uncontrolled)', 'Cancer', 'Pregnancy'],
  },
  {
    id: 'igf-1-lr3',
    name: 'IGF-1 LR3',
    fullName: 'Insulin-like Growth Factor 1 Long R3',
    aliases: ['IGF', 'Long R3 IGF-1', 'IGF1 LR3'],
    category: 'muscle',
    fdaApproved: false,
    safetyRating: 2,
    mechanism: 'Modified version of IGF-1 with extended half-life. Directly stimulates muscle cell hyperplasia (new muscle cell creation) and has potent anabolic effects independent of GH.',
    benefits: ['Muscle hyperplasia (new cells)', 'Enhanced recovery', 'Increased protein synthesis', 'Fat loss', 'Improved nutrient partitioning'],
    sideEffects: ['Hypoglycemia (serious)', 'Joint pain', 'Jaw/hand growth (prolonged use)', 'Organ growth risk', 'Gut distension (high doses)'],
    typicalDose: { min: 20, max: 80, unit: 'mcg', startingDose: '20-40mcg post-workout' },
    frequency: 'Daily or training days only',
    cycleLength: '4-6 weeks on, 4 weeks off',
    halfLife: '~20-30 hours',
    injectionType: 'Subcutaneous or intramuscular',
    timing: 'Post-workout with carbohydrates',
    reconstitution: { powderMg: 1, waterMl: 1, concentrationPerMl: '1mg/mL' },
    storage: { refrigerated: true, shelfLife: '28 days reconstituted', freezer: 'Up to 12 months lyophilized' },
    stacksWith: ['bpc-157', 'mk-677'],
    contraindications: ['Diabetes', 'Active cancer', 'Pregnancy', 'History of hypoglycemia'],
  },
  {
    id: 'enclomiphene',
    name: 'Enclomiphene',
    fullName: 'Enclomiphene Citrate',
    aliases: ['Enclom', 'Androxal'],
    category: 'hormone',
    fdaApproved: false,
    safetyRating: 4,
    mechanism: 'Selective estrogen receptor modulator (SERM) that blocks estrogen feedback at the hypothalamus and pituitary, stimulating increased LH and FSH production, leading to higher natural testosterone.',
    benefits: ['Increases natural testosterone', 'Preserves fertility (unlike TRT)', 'Maintains testicular function', 'Oral dosing', 'Well-studied compound'],
    sideEffects: ['Headache', 'Hot flashes', 'Mood changes', 'Visual disturbances (rare)', 'GI upset'],
    typicalDose: { min: 12.5, max: 25, unit: 'mg', startingDose: '12.5mg daily' },
    frequency: 'Daily (oral)',
    cycleLength: 'Ongoing or 8-12 week cycles',
    halfLife: '~10 hours',
    injectionType: 'Oral',
    timing: 'Morning with food',
    reconstitution: null,
    storage: { refrigerated: false, shelfLife: 'Per bottle expiry', freezer: 'Not required' },
    stacksWith: [],
    contraindications: ['Liver disease', 'Hormone-sensitive cancers', 'Pregnancy', 'Blood clotting disorders'],
  },
  {
    id: 'aod-9604',
    name: 'AOD-9604',
    fullName: 'Advanced Obesity Drug 9604',
    aliases: ['AOD', 'Anti-Obesity Drug', 'hGH Fragment 176-191'],
    category: 'fat_loss',
    fdaApproved: false,
    safetyRating: 4,
    mechanism: 'Modified fragment of human growth hormone (amino acids 176-191) that stimulates lipolysis and inhibits lipogenesis without the metabolic effects of full GH (no blood sugar impact).',
    benefits: ['Targets fat reduction', 'No blood sugar impact', 'No muscle hypertrophy effects', 'Stimulates fat metabolism', 'Supports cartilage repair'],
    sideEffects: ['Injection site irritation', 'Headache (mild)', 'Generally very well tolerated'],
    typicalDose: { min: 250, max: 500, unit: 'mcg', startingDose: '300mcg daily' },
    frequency: 'Daily',
    cycleLength: '12-20 weeks',
    halfLife: '~1 hour',
    injectionType: 'Subcutaneous',
    timing: 'Morning on empty stomach (30 min before food)',
    reconstitution: { powderMg: 5, waterMl: 2.5, concentrationPerMl: '2mg/mL' },
    storage: { refrigerated: true, shelfLife: '21 days reconstituted', freezer: 'Up to 12 months lyophilized' },
    stacksWith: ['bpc-157', 'tesamorelin'],
    contraindications: ['Active cancer', 'Pregnancy'],
  },
  {
    id: 'sermorelin',
    name: 'Sermorelin',
    fullName: 'Sermorelin Acetate',
    aliases: ['Geref', 'GRF 1-29'],
    category: 'anti_aging',
    fdaApproved: true,
    safetyRating: 5,
    mechanism: 'Bioidentical GHRH (first 29 amino acids) that stimulates natural GH production from the pituitary. Preserves the natural GH pulsatile pattern and feedback mechanisms.',
    benefits: ['Increases natural GH production', 'Improved sleep quality', 'Enhanced recovery', 'Better skin elasticity', 'Supports lean body mass', 'FDA-approved safety record'],
    sideEffects: ['Injection site reactions', 'Facial flushing', 'Headache', 'Dizziness', 'Sleepiness'],
    typicalDose: { min: 200, max: 500, unit: 'mcg', startingDose: '300mcg before bed' },
    frequency: 'Daily',
    cycleLength: '3-6 months, can use long-term',
    halfLife: '~10-20 minutes',
    injectionType: 'Subcutaneous',
    timing: 'Before bed on empty stomach',
    reconstitution: { powderMg: 5, waterMl: 2.5, concentrationPerMl: '2mg/mL' },
    storage: { refrigerated: true, shelfLife: '21 days reconstituted', freezer: 'Up to 12 months lyophilized' },
    stacksWith: ['ipamorelin', 'ghk-cu', 'bpc-157'],
    contraindications: ['Active malignancy', 'Pregnancy', 'Pituitary disorders'],
  },
];

window.PEPTIDE_MAP = {};
window.PEPTIDE_LIBRARY.forEach(function(p) { window.PEPTIDE_MAP[p.id] = p; });

// User's default protocol
window.DEFAULT_PROTOCOL = [
  {
    id: 'proto_reta',
    peptideId: 'retatrutide',
    name: 'Retatrutide',
    doseAmount: 1,
    doseUnit: 'mg',
    targetDose: 2,
    frequency: 'weekly',
    timeOfDay: 'any',
    timing: 'Any time, same day each week',
    active: true,
    phase: 1,
    startDate: '',
    notes: 'Starting 1mg, titrating to 2mg over 4 weeks',
    fdaApproved: false,
  },
  {
    id: 'proto_tesa_ipa',
    peptideId: 'tesamorelin',
    name: 'Tesamorelin + Ipamorelin',
    doseAmount: 2,
    doseUnit: 'mg',
    frequency: 'daily',
    timeOfDay: 'evening',
    timing: 'Before bed on empty stomach',
    active: true,
    phase: 1,
    startDate: '',
    notes: 'Combined GH secretagogue stack',
    fdaApproved: true,
    secondPeptideId: 'ipamorelin',
  },
  {
    id: 'proto_bpc_tb',
    peptideId: 'bpc-157',
    name: 'BPC-157 + TB-500',
    doseAmount: 250,
    doseUnit: 'mcg',
    frequency: 'daily',
    timeOfDay: 'any',
    timing: 'Any time of day',
    active: true,
    phase: 1,
    startDate: '',
    notes: 'Recovery and healing stack',
    fdaApproved: false,
    secondPeptideId: 'tb-500',
  },
  {
    id: 'proto_ghk',
    peptideId: 'ghk-cu',
    name: 'GHK-Cu',
    doseAmount: 2,
    doseUnit: 'mg',
    frequency: 'daily',
    timeOfDay: 'any',
    timing: 'Any time of day',
    active: true,
    phase: 1,
    startDate: '',
    notes: 'Anti-aging and skin rejuvenation',
    fdaApproved: false,
  },
  {
    id: 'proto_cjc_ipa_p2',
    peptideId: 'cjc-1295',
    name: 'CJC-1295 + Ipamorelin',
    doseAmount: 100,
    doseUnit: 'mcg',
    frequency: 'daily',
    timeOfDay: 'evening',
    timing: 'Before bed on empty stomach',
    active: false,
    phase: 2,
    notes: '12 weeks on, 4 weeks off cycle',
    fdaApproved: false,
    secondPeptideId: 'ipamorelin',
  },
];

// Milestone definitions
window.MILESTONES = [
  { id: 'first_injection', label: 'First Injection', icon: '💉', condition: function(data) { return data.totalInjections >= 1; } },
  { id: 'week_streak', label: '1 Week Streak', icon: '🔥', condition: function(data) { return data.currentStreak >= 7; } },
  { id: 'two_week_streak', label: '2 Week Streak', icon: '⚡', condition: function(data) { return data.currentStreak >= 14; } },
  { id: 'one_month', label: '1 Month on Protocol', icon: '📅', condition: function(data) { return data.daysOnProtocol >= 30; } },
  { id: 'two_months', label: '2 Months on Protocol', icon: '🏆', condition: function(data) { return data.daysOnProtocol >= 60; } },
  { id: 'three_months', label: '3 Months on Protocol', icon: '👑', condition: function(data) { return data.daysOnProtocol >= 90; } },
  { id: 'five_lbs', label: 'First 5 lbs Lost', icon: '⬇️', condition: function(data) { return data.totalWeightLost >= 5; } },
  { id: 'ten_lbs', label: '10 lbs Lost', icon: '🎯', condition: function(data) { return data.totalWeightLost >= 10; } },
  { id: 'fifteen_lbs', label: '15 lbs Lost', icon: '💪', condition: function(data) { return data.totalWeightLost >= 15; } },
  { id: 'twenty_lbs', label: '20 lbs Lost', icon: '🏅', condition: function(data) { return data.totalWeightLost >= 20; } },
  { id: 'twenty_five_lbs', label: '25 lbs Lost', icon: '⭐', condition: function(data) { return data.totalWeightLost >= 25; } },
  { id: 'protein_7days', label: '7-Day Protein Streak', icon: '🥩', condition: function(data) { return data.proteinStreak >= 7; } },
];
